version: "3.7"
services:
  cledge:
    container_name: cledge
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src
    env_file:
      - ./src/config/.env.local
