export const accountQuestions = [
  {
    question: "ADDRESS",
    type: "CompositeQuestion",
    data: [
      {
        _id: "zip-code",
        question: "Zip Code",
        type: "TextInput",
        helpVid: "",
        helpText: "123456",
        data: [],
        isConcatenable: false,
      },
      {
        _id: null,
        question: "",
        type: "DoubleDropdownQuestion",
        helpVid: "",
        helpText: "",
        data: [
          {
            _id: 0,
            question: "State",
            type: "DropDownQuestion",
            helpVid: "",
            helpText: "",
            data: [
              "AL – Alabama",
              "AK – Alaska",
              "AZ – Arizona",
              "AR – Arkansas",
              "CA – California",
              "CO – Colorado",
              "CT – Connecticut",
              "DE – Delaware",
              "FL – Florida",
              "GA – Georgia",
              "HI – Hawaii",
              "ID – Idaho",
              "IL – Illinois",
              "IN – Indiana",
              "IA – Iowa",
              "KS – Kansas",
              "KY – Kentucky",
              "LA – Louisiana",
              "ME – Maine",
              "MD – Maryland",
              "MA – Massachusetts",
              "MI – Michigan",
              "MN – Minnesota",
              "MS – Mississippi",
              "MO – Missouri",
              "MT – Montana",
              "NE – Nebraska",
              "NV – Nevada",
              "NH – New Hampshire",
              "NJ – New Jersey",
              "NM – New Mexico",
              "NY – New York",
              "NC – North Carolina",
              "ND – North Dakota",
              "OH – Ohio",
              "OK – Oklahoma",
              "OR – Oregon",
              "PA – Pennsylvania",
              "RI – Rhode Island",
              "SC – South Carolina",
              "SD – South Dakota",
              "TN – Tennessee",
              "TX – Texas",
              "UT – Utah",
              "VT – Vermont",
              "VA – Virginia",
              "WA – Washington",
              "WV – West Virginia",
              "WI – Wisconsin",
              "WY – Wyoming",
            ],
            isConcatenable: false,
          },
          {
            _id: 1,
            question: "Country",
            type: "DropDownQuestion",
            helpVid: "",
            helpText: "",
            data: ["United States", "Other"],
            isConcatenable: false,
          },
        ],
        isConcatenable: false,
      },
    ],
  },
  {
    question: "NAME",
    type: "DoubleTextInputQuestion",
    data: [
      {
        _id: 0,
        question: "First Name",
        type: "TextInputQuestion",
        helpVid: "",
        helpText: "",
        data: [""],
        isConcatenable: false,
      },
      {
        _id: 1,
        question: "Last Name",
        type: "TextInputQuestion",
        helpVid: "",
        helpText: "",
        data: [""],
        isConcatenable: false,
      },
    ],
  },
  {
    data: [
      {
        tag: "9th",
        op: "9th grade",
      },
      {
        op: "10th grade ",
        tag: "10th",
      },
      {
        tag: "11th",
        op: "11th grade",
      },
      {
        op: "12th grade",
        tag: "12th",
      },
    ],
    type: "MCQ",
    question: "Grade",
  },
];
